[cmd_duration]
disabled = true

[git_branch]
disabled = true

# Disable Git commit information
[git_commit]
disabled = true

# Don't print a new âœline at the start of the prompt
add_newline = false

[character] # The name of the module we are configuring is 'character'
# success_symbol = '[ğŸ§ğŸ‘»ğŸ‘ï¸ğŸ¤ŒğŸ—¿ğŸŒğŸ›¹](bold green)'
success_symbol = '[ğŸ‘ï¸](bold green)'

# Disable the package module, hiding the version of the current package
[package]
disabled = false

[[battery.display]] # 'bold red' style and discharging_symbol when capacity is between 0% and 10%
threshold = 30
style = 'bold red'
discharging_symbol = 'ğŸ’€ '

[[battery.display]] # 'bold yellow' style and ğŸ’¦ symbol when capacity is between 10% and 30%
threshold = 60
style = 'bold yellow'
discharging_symbol = 'â˜¢ï¸ '

[[battery.display]]
threshold = 90
style = 'bold green'
discharging_symbol = 'âœ¨ '

# when capacity is over 60%, the battery indicator will not be displayed

[battery]
full_symbol = 'ğŸ”‹ '
charging_symbol = 'âš¡ï¸ '
discharging_symbol = 'ğŸ’€ '

[directory]
truncation_length = 8
truncation_symbol = 'â€¦/'

[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue) on [$hostname](bold red) '
trim_at = '.companyname.com'
disabled = false

# ~/.config/starship.toml

[time]
disabled = false
format = '[$time]($style) '
time_format = '%r'
style = 'bold purple'
